# config.py

BOT_API_KEY = '[INSERT_YOUR_BOT_API_KEY_HERE]'
CALLS_CHANNEL_NAME = '[INSERT_YOUR_CALLS_CHANNEL_NAME_HERE]'
PUBLIC_CHANNEL_NAME = '[INSERT_YOUR_PUBLIC_CHANNEL_NAME_HERE]'
HOST="[DATABASE_HOST]"
USER="[DATABASE_USER]"
PASSWORD="[DATABASE_PASSWORD]"
DATABASE="[DATABASE_NAME]"
PROFIT_TRESHOLD = 50